html,text/html
txt,text/plain
css,text/css
js,application/javascript
json,application/json
xml,application/xml
pdf,application/pdf
jpg,image/jpeg
jpeg,image/jpeg
aviff,image/aviff
avif,image/avif
png,image/png
gif,image/gif
svg,image/svg+xml
mp4,video/mp4
mp3,audio/mpeg
wav,audio/wav
zip,application/zip
doc,application/msword
docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document
xls,application/vnd.ms-excel
xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
ppt,application/vnd.ms-powerpoint
pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation
csv,text/csv
rtf,application/rtf
tar,application/x-tar
gz,application/gzip
7z,application/x-7z-compressed
rar,application/vnd.rar
ogg,audio/ogg
webm,video/webm
bmp,image/bmp
ico,image/x-icon
psd,image/vnd.adobe.photoshop
ai,application/postscript
eps,application/postscript
tif,image/tiff
tiff,image/tiff
webp,image/webp
svg,image/svg+xml
txt,text/plain
csv,text/csv
log,text/plain
ini,text/plain
conf,text/plain
sh,application/x-shellscript
bat,application/bat
dll,application/octet-stream
exe,application/octet-stream
deb,application/x-deb
rpm,application/x-rpm
apk,application/vnd.android.package-archive
iso,application/octet-stream
torrent,application/x-bittorrent
ics,text/calendar
vcf,text/vcard
m3u,audio/x-mpegurl
m4a,audio/mp4a-latm
wma,audio/x-ms-wma
wmv,video/x-ms-wmv
